name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'imbhargav5/nextbase-nextjs13-supabase-starter'}}
    steps:
      - name: ğŸš‚ CI Setup
        uses: ./.github/actions/ci-setup
      - name: âš›ï¸ Install packages
        uses: ./.github/actions/install-packages
      - name: âš›ï¸ Install packages
        uses: ./.github/actions/ci-setup
      - run: yarn run build

  test:
    strategy:
      matrix:
        node-version: [18.x]

    name: Run all tests
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'imbhargav5/nextbase-nextjs13-supabase-starter'}}
    steps:
      - name: ğŸš‚ CI Setup
        uses: ./.github/actions/ci-setup
      - name: âš›ï¸ Install packages
        uses: ./.github/actions/install-packages
      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Linter
        run: yarn run lint

      - name: Type checking
        run: yarn run tsc

      - name: Run unit tests
        run: yarn run test
      - name: Install playwright browsers
        run: yarn playwright install --with-deps

      - name: Run e2e tests
        run: yarn run test:e2e
