name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  update:
    strategy:
      matrix:
        node-version: [18.x]

    name: Update all dependencies
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'imbhargav5/nextbase-nextjs13-supabase-starter'}}
    steps:
      - name: ğŸš‚ CI Setup
        uses: ./.github/actions/ci-setup
      - name: âš›ï¸ Install packages
        uses: ./.github/actions/install-packages
      - run: yarn npm-check-updates -u # Update dependencies
      - run: rm -Rf node_modules yarn.lock
      - run: yarn
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'build: update dependencies to the latest version'
          title: Update dependencies to the latest version
